baseURL = "https://facebook.tracking.exposed/"
languageCode = "en-us"
title = "Tracking Exposed"
theme = "trex"
enableRobotsTXT = true
canonifyURLs = true
[params]
    subtitle = "facebook"
    description = "Facebook Tracking Exposed is a web browser addon that collects the stories visible in your Facebook News feed and a website that aggregates that data from all the users who have the addon installed. Our vision is to increase transparency behind personalization algorithms"
    subsite = "true"
    background = "#FFF"
    primary = "#3C5A96"
    primary_light = ""
    secondary = ""
    tertiary_dark = ""
    tertiary = ""

[permalinks]
    posts = "/:slug/"

#sectionPagesMenu = "main"


[menu]
 [[menu.main]]
    page = "Reality Check"
    identifier = "reality-check"
    name= "Reality Check"
    url = "/reality-check/"
    weight = -180
 [[menu.main]]
    page = "Zuckless News"
    identifier = "zuckless-news"
    name = "Zuckless News"
    url = "/zuckless-news/"
    weight = -170
 [[menu.main]]
    page = "Analysis & Publications"
    identifier = "analysis-and-publications"
    name = "Analysis & Publications"
    url = "/analysis-and-publications/"
    weight = -160
 [[menu.main]]
    page = "More"
    identifier = "more"
    name = "More"
    url = "#"
    weight = -100
 [[menu.main]]
    page = "About"
    identifier = "about"
    name = "About"
    url = "/about/"
    parent = "more"
    weight = -110
 [[menu.main]]
    page = "Data Activism"
    identifier = "Data Activism"
    parent = "more"
    name = "Data Activism"
    url = "/data-activism/"
    weight = -120
 [[menu.main]]
    page = "API Documentation"
    identifier = "api-documentation"
    parent = "more"
    name = "API Documentation"
    url = "/api-documentation/"
    weight = -130
 [[menu.main]]
    page = "Get Involved"
    identifier = "get-involved"
    name = "Get Involved"
    parent = "more"
    url = "/get-involved/"
    weight = -140
 [[menu.main]]
    page = "Impact"
    identifier = "impact"
    name = "Impact"
    parent = "more"
    url = "/impact/"
    weight = -150
 [[menu.main]]
    page = "What We Collect"
    identifier = "what-we-collect"
    name = "What We Collect"
    parent = "more"
    url = "/what-we-collect/"
    weight = -150


 [[menu.footer]]
    page = "executive-summary"
    identifier = "executive-summary"
    name = "Project Summary"
    url = "/background/summary"
    weight = -140

 [[menu.footer]]
    page = "glossary"
    identifier = "glossaty"
    name = "Glossary"
    url = "/background/glossary"
    weight = -130

 [[menu.footer]]
    page = "problem"
    identifier = "problem"
    name = "Problem definition"
    url = "/background/problem"
    weight = -120

 [[menu.footer]]
    page = "solution"
    identifier = "solution"
    name = "Mandate/Solution"
    url = "/background/solution"
    weight = -110

 [[menu.footer]]
    page = "ethics"
    identifier = "ethics"
    name = "Our Ethics"
    url = "/background/ethics"
    weight = -100

 [[menu.footer]]
    page = "get-the-extension"
    identifier = "get-the-extension"
    name = "Get the extension"
    url = "/background/get-the-extension/"
    weight = -90
